INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('-1','---','Mundial');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('AD','AND','Andorra');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('AE','ARE','Emiratos Árabes Unidos');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('AF','AFG','Afganistán');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('AG','ATG','Antigua y Barbuda');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('AI','AIA','Anguila');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('AL','ALB','Albania');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('AM','ARM','Armenia');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('AN','ANT','Antillas Neerlandesas');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('AO','AGO','Angola');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('AQ','ATA','Antártida');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('AR','ARG','Argentina');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('AS','ASM','Samoa Americana');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('AT','AUT','Austria');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('AU','AUS','Australia');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('AW','ABW','Aruba');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('AX','ALA','Islas Åland');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('AZ','AZE','Azerbaiyán');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('BA','BIH','Bosnia-Herzegovina');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('BB','BRB','Barbados');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('BD','BGD','Bangladesh');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('BE','BEL','Bélgica');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('BF','BFA','Burkina Faso');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('BG','BGR','Bulgaria');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('BH','BHR','Bahréin');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('BI','BDI','Burundi');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('BJ','BEN','Benín');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('BL','BLM','San Bartolomé');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('BM','BMU','Bermudas');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('BN','BRN','Brunéi');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('BO','BOL','Bolivia');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('BR','BRA','Brasil');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('BS','BHS','Bahamas');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('BT','BTN','Bután');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('BV','BVT','Isla Bouvet');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('BW','BWA','Botsuana');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('BY','BLR','Bielorrusia');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('BZ','BLZ','Belice');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('CA','CAN','Canadá');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('CC','CCK','Islas Cocos');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('CD','COD','República Democrática del Congo');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('CF','CAF','República Centroafricana');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('CG','COG','Congo');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('CH','CHE','Suiza');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('CI','CIV','Costa de Marfil');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('CK','COK','Islas Cook');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('CL','CHL','Chile');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('CM','CMR','Camerún');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('CN','CHN','China');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('CO','COL','Colombia');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('CR','CRI','Costa Rica');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('CS','SCG','Serbia y Montenegro');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('CU','CUB','Cuba');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('CV','CPV','Cabo Verde');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('CX','CXR','Isla Christmas');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('CY','CYP','Chipre');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('CZ','CZE','República Checa');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('DE','DEU','Alemania');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('DJ','DJI','Yibuti');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('DK','DNK','Dinamarca');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('DM','DMA','Dominica');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('DO','DOM','República Dominicana');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('DZ','DZA','Argelia');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('EC','ECU','Ecuador');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('EE','EST','Estonia');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('EG','EGY','Egipto');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('EH','ESH','Sáhara Occidental');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('ER','ERI','Eritrea');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('ES','ESP','España');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('ET','ETH','Etiopía');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('FI','FIN','Finlandia');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('FJ','FJI','Fiyi');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('FK','FLK','Islas Malvinas');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('FM','FSM','Micronesia');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('FO','FRO','Islas Feroe');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('FR','FRA','Francia');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('GA','GAB','Gabón');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('GB','GBR','Reino Unido');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('GD','GRD','Granada');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('GE','GEO','Georgia');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('GF','GUF','Guayana Francesa');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('GG','GGY','Guernsey');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('GH','GHA','Ghana');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('GI','GIB','Gibraltar');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('GL','GRL','Groenlandia');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('GM','GMB','Gambia');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('GN','GIN','Guinea');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('GP','GLP','Guadalupe');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('GQ','GNQ','Guinea Ecuatorial');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('GR','GRC','Grecia');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('GS','SGS','Islas Georgia del Sur y Sandwich del Sur');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('GT','GTM','Guatemala');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('GU','GUM','Guam');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('GW','GNB','Guinea-Bissau');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('GY','GUY','Guyana');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('HK','HKG','Hong Kong');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('HM','HMD','Islas Heard y McDonald');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('HN','HND','Honduras');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('HR','HRV','Croacia');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('HT','HTI','Haití');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('HU','HUN','Hungría');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('ID','IDN','Indonesia');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('IE','IRL','Irlanda');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('IL','ISR','Israel');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('IM','IMN','Isla de Man');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('IN','IND','India');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('IO','IOT','Territorio Británico del Océano Índico');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('IQ','IRQ','Iraq');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('IR','IRN','Irán');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('IS','ISL','Islandia');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('IT','ITA','Italia');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('JE','JEY','Jersey');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('JM','JAM','Jamaica');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('JO','JOR','Jordania');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('JP','JPN','Japón');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('KE','KEN','Kenia');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('KG','KGZ','Kirguistán');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('KH','KHM','Camboya');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('KI','KIR','Kiribati');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('KM','COM','Comoras');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('KN','KNA','San Cristóbal y Nieves');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('KP','PRK','Corea del Norte');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('KR','KOR','Corea del Sur');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('KW','KWT','Kuwait');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('KY','CYM','Islas Caimán');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('KZ','KAZ','Kazajistán');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('LA','LAO','Laos');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('LB','LBN','Líbano');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('LC','LCA','Santa Lucía');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('LI','LIE','Liechtenstein');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('LK','LKA','Sri Lanka');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('LR','LBR','Liberia');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('LS','LSO','Lesoto');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('LT','LTU','Lituania');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('LU','LUX','Luxemburgo');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('LV','LVA','Letonia');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('LY','LBY','Libia');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('MA','MAR','Marruecos');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('MC','MCO','Mónaco');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('MD','MDA','Moldavia');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('ME','MNE','Montenegro');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('MF','MAF','San Martín');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('MG','MDG','Madagascar');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('MH','MHL','Islas Marshall');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('MK','MKD','Macedonia');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('ML','MLI','Mali');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('MM','MMR','Myanmar');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('MN','MNG','Mongolia');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('MO','MAC','Macao');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('MP','MNP','Islas Marianas del Norte');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('MQ','MTQ','Martinica');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('MR','MRT','Mauritania');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('MS','MSR','Montserrat');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('MT','MLT','Malta');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('MU','MUS','Mauricio');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('MV','MDV','Maldivas');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('MW','MWI','Malaui');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('MX','MEX','México');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('MY','MYS','Malasia');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('MZ','MOZ','Mozambique');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('NA','NAM','Namibia');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('NC','NCL','Nueva Caledonia');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('NE','NER','Níger');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('NF','NFK','Isla Norfolk');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('NG','NGA','Nigeria');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('NI','NIC','Nicaragua');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('NL','NLD','Países Bajos');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('NO','NOR','Noruega');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('NP','NPL','Nepal');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('NR','NRU','Nauru');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('NU','NIU','Isla Niue');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('NZ','NZL','Nueva Zelanda');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('OM','OMN','Omán');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('PA','PAN','Panamá');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('PE','PER','Perú');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('PF','PYF','Polinesia Francesa');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('PG','PNG','Papúa Nueva Guinea');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('PH','PHL','Filipinas');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('PK','PAK','Pakistán');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('PL','POL','Polonia');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('PM','SPM','San Pedro y Miquelón');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('PN','PCN','Pitcairn');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('PR','PRI','Puerto Rico');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('PS','PSE','Palestina');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('PT','PRT','Portugal');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('PW','PLW','Palau');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('PY','PRY','Paraguay');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('QA','QAT','Qatar');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('RE','REU','Reunión');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('RO','ROU','Rumanía');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('RS','SRB','Serbia');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('RU','RUS','Rusia');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('RW','RWA','Ruanda');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('SA','SAU','Arabia Saudí');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('SB','SLB','Islas Salomón');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('SC','SYC','Seychelles');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('SD','SDN','Sudán');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('SE','SWE','Suecia');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('SG','SGP','Singapur');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('SH','SHN','Santa Elena');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('SI','SVN','Eslovenia');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('SJ','SJM','Svalbard y Jan Mayen');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('SK','SVK','Eslovaquia');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('SL','SLE','Sierra Leona');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('SM','SMR','San Marino');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('SN','SEN','Senegal');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('SO','SOM','Somalia');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('SR','SUR','Surinam');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('ST','STP','Santo Tomé y Príncipe');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('SV','SLV','El Salvador');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('SY','SYR','Siria');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('SZ','SWZ','Suazilandia');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('TC','TCA','Islas Turcas y Caicos');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('TD','TCD','Chad');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('TF','ATF','Territorios Australes Franceses');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('TG','TGO','Togo');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('TH','THA','Tailandia');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('TJ','TJK','Tayikistán');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('TK','TKL','Tokelau');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('TL','TLS','Timor Oriental');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('TM','TKM','Turkmenistán');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('TN','TUN','Túnez');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('TO','TON','Tonga');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('TR','TUR','Turquía');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('TT','TTO','Trinidad y Tobago');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('TV','TUV','Tuvalu');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('TW','TWN','Taiwán');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('TZ','TZA','Tanzania');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('UA','UKR','Ucrania');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('UG','UGA','Uganda');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('UM','UMI','Islas menores alejadas de los Estados Unidos');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('US','USA','Estados Unidos');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('UY','URY','Uruguay');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('UZ','UZB','Uzbekistán');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('VA','VAT','Ciudad del Vaticano');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('VC','VCT','San Vicente y las Granadinas');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('VE','VEN','Venezuela');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('VG','VGB','Islas Vírgenes Británicas');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('VI','VIR','Islas Vírgenes de los Estados Unidos');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('VN','VNM','Vietnam');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('VU','VUT','Vanuatu');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('WF','WLF','Wallis y Futuna');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('WS','WSM','Samoa');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('YE','YEM','Yemen');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('YT','MYT','Mayotte');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('ZA','ZAF','Sudáfrica');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('ZM','ZMB','Zambia');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('ZW','ZWE','Zimbabue');
INSERT INTO country (iso_alpha2,iso_alpha3,name) VALUES ('ZZ','ZZZ','Región desconocida o no válida');
